name: allcoderelay
description: "Universal code scanner with webhook integration"
publish_to: "none"
version: 1.1.0+10

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0 # Update to latest version
  cupertino_icons: ^1.0.8
  mobile_scanner: ^7.0.1 # For 2D/3D code scanning
  # nfc_manager: ^3.3.0 # For NFC reading
  http: ^1.2.0 # For webhook communication
  # firebase_core: ^2.24.2
  # firebase_messaging: ^14.7.10
  shared_preferences: ^2.2.2 # For storing settings
  flutter_bloc: ^9.1.1 # For state management
  go_router: ^17.1.0 # For navigation
  flutter_secure_storage: ^10.0.0 # For secure storage of webhook URL
  package_info_plus: ^9.0.0
  share_plus: ^12.0.1
  sqflite: ^2.3.2
  path: ^1.8.3
  url_launcher: ^6.2.4
  app_links: ^7.0.0

  provider: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
